scrape_configs:
  - job_name: 'gateway'
    metrics_path: /actuator/prometheus
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.29.196:8070']
  - job_name: 'rajatsproductservice'
    metrics_path: /actuator/prometheus
    scrape_interval: 1s
    static_configs:
      - targets: [ '192.168.29.196:5100' ]